#!/usr/bin/env python3
import logging
import requests
from pydantic import BaseModel, Field
import uvicorn
import time
import uuid 

# Note: We are NOT using FastMCP here because this script is purely an OpenAI-compatible adapter for Open WebUI.
# The true MCP server with FastMCP for Cursor will be a different file (mcp_server_main.py).
# import memory_bank_tool_backend as memory_backend # Assuming this is in the same directory
# import ollama # Assuming ollama is installed

# For this script, let's embed the memory and RAG logic directly for simplicity if it's ONLY for OpenWebUI
# to avoid running too many separate servers.
# However, if rag_api_server.py and memory_bank_tool_backend.py are robust, we can call them.
# For now, sticking to calling rag_api_server.py and using memory_bank_tool_backend.py directly.

import memory_bank_tool_backend as memory_backend 
import ollama 


# --- Configuration ---
RAG_API_SERVER_URL = "http://127.0.0.1:8008/retrieve" # Your RAG server
# Use the RAG API Key generated by python_generate_keys.py
RAG_API_KEY = "f5wlJhj_tbVh3Nmk-jUNbCYg9CWG7A-KXudQJV4BJxo"  # <<< REPLACE THIS
RAG_API_KEY_NAME = "X-RAG-API-Key" # Must match what rag_api_server.py expects

OPENWEBUI_ADAPTER_PORT = 8009 # Port this adapter server will run on
LLM_MODEL_NAME = "gemma3:12b-it-qat" # LLM for this adapter
DEFAULT_RAG_N_RESULTS = 3
DEFAULT_MEMORY_N_RESULTS = 3

# --- Logging Setup ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("OpenWebUI_Adapter")
logging.getLogger("requests").setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("chromadb").setLevel(logging.WARNING)
logging.getLogger("ollama").setLevel(logging.WARNING)


# --- FastAPI App for OpenWebUI Adapter ---
from fastapi import FastAPI # Ensure FastAPI is imported

app = FastAPI(
    title="OpenWebUI Adapter for Gemma with RAG & Memory",
    description="Provides an OpenAI-compatible API endpoint for OpenWebUI, using local RAG and Memory.",
    version="0.1.0"
)

# --- OpenAI-Compatible API Schemas (Same as before) ---
class OpenAIChatMessage(BaseModel):
    role: str
    content: str

class OpenAIChatCompletionRequest(BaseModel):
    model: str
    messages: list[OpenAIChatMessage]
    stream: bool = False

class OpenAIChatCompletionChoice(BaseModel):
    index: int
    message: OpenAIChatMessage
    finish_reason: str = "stop"

class OpenAIUsage(BaseModel):
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0

class OpenAIChatCompletionResponse(BaseModel):
    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex}")
    object: str = "chat.completion"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str
    choices: list[OpenAIChatCompletionChoice]
    usage: OpenAIUsage = Field(default_factory=OpenAIUsage)


# --- Helper functions ---
def query_rag_api_internal(user_query: str, n_results: int = DEFAULT_RAG_N_RESULTS) -> list[dict]:
    payload = {"query": user_query, "n_results": n_results}
    headers = {RAG_API_KEY_NAME: RAG_API_KEY}
    retrieved_chunks = []
    try:
        logger.info(f"Adapter: Querying RAG API at {RAG_API_SERVER_URL} for: '{user_query[:50]}...'")
        response = requests.post(RAG_API_SERVER_URL, json=payload, headers=headers, timeout=30)
        response.raise_for_status()
        data = response.json()
        retrieved_chunks = data.get("retrieved_chunks", [])
        logger.info(f"Adapter: RAG API returned {len(retrieved_chunks)} chunks.")
    except requests.exceptions.HTTPError as http_err:
        if http_err.response.status_code == 403:
            logger.error(f"Adapter: RAG query failed: 403 Forbidden. Check RAG_API_KEY. Key starts with: '{RAG_API_KEY[:5]}...'")
        else:
            logger.error(f"Adapter: RAG query failed with HTTP error: {http_err}")
    except Exception as e:
        logger.error(f"Adapter: RAG query failed: {e}")
    return retrieved_chunks

def format_combined_context_for_llm(user_query: str, memories: list[dict], rag_chunks: list[dict]) -> str:
    context_str = ""
    if memories:
        context_str += "Relevant information from past interactions (memory bank):\n"
        for i, mem_entry in enumerate(memories):
            metadata = mem_entry.get('metadata', {})
            context_str += f"---\nMemory {i+1} (Source: {metadata.get('source', 'unknown')}, Timestamp: {metadata.get('timestamp', 'N/A')}):\n"
            context_str += f"Content: {mem_entry.get('text', '')}\n"
        context_str += "---\n\n"
    if rag_chunks:
        context_str += "Context from knowledge base (RAG):\n"
        for i, chunk in enumerate(rag_chunks):
            context_str += f"---\nKnowledge Chunk {i+1}:\n"
            if chunk.get('repo_source'): context_str += f"Source Type: {chunk.get('repo_source')}\n"
            elif chunk.get('source_type'): context_str += f"Source Type: {chunk.get('source_type')}\n"
            context_str += f"Path/Identifier: {chunk.get('source_path', 'N/A')}\n"
            if chunk.get('document_title'): context_str += f"Document Title: {chunk.get('document_title')}\n"
            context_str += f"Content: {chunk.get('text', '')}\n"
        context_str += "---\n\n"
    if not context_str:
        return "You are a helpful AI assistant. Answer the user's question based on your general knowledge."
    return f"{context_str}You are a helpful AI assistant. Based on the context above (if relevant) and your general knowledge, answer the user's question."

# --- OpenAI-Compatible Chat Completions Endpoint ---
@app.post("/v1/chat/completions", response_model=OpenAIChatCompletionResponse)
async def openai_chat_completions(request: OpenAIChatCompletionRequest):
    logger.info(f"Adapter: Received OpenAI-compatible request for model: {request.model}, stream: {request.stream}")
    if request.stream:
        logger.warning("Adapter: Streaming requested but not implemented. Returning non-streamed response.")

    user_query = ""
    if request.messages:
        for msg in reversed(request.messages):
            if msg.role == "user": user_query = msg.content; break
    if not user_query: raise HTTPException(status_code=400, detail="No user query in messages.")
    logger.info(f"Adapter: Extracted user query: '{user_query[:100]}...'")

    retrieved_memories = memory_backend.retrieve_relevant_memory_entries(user_query, n_results=DEFAULT_MEMORY_N_RESULTS)
    logger.info(f"Adapter: Retrieved {len(retrieved_memories)} memories.")
    
    rag_chunks = query_rag_api_internal(user_query, n_results=DEFAULT_RAG_N_RESULTS) # Uses API Key
    logger.info(f"Adapter: Retrieved {len(rag_chunks)} RAG chunks.")

    system_prompt_content = format_combined_context_for_llm(user_query, retrieved_memories, rag_chunks)
    
    llm_messages = [
        {'role': 'system', 'content': system_prompt_content},
        {'role': 'user', 'content': user_query}
    ]
    
    logger.info(f"Adapter: Asking LLM '{LLM_MODEL_NAME}' via Ollama.")
    try:
        ollama_response = ollama.chat(model=LLM_MODEL_NAME, messages=llm_messages)
        llm_content = ollama_response['message']['content']
    except Exception as e:
        logger.error(f"Adapter: Error calling Ollama: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Error with local LLM: {str(e)}")

    response_choice = OpenAIChatCompletionChoice(index=0, message=OpenAIChatMessage(role="assistant", content=llm_content))
    return OpenAIChatCompletionResponse(model=LLM_MODEL_NAME, choices=[response_choice])

@app.on_event("startup")
async def startup_event():
    logger.info(f"OpenWebUI Adapter starting on port {OPENWEBUI_ADAPTER_PORT}...")
    if RAG_API_KEY == "PASTE_YOUR_GENERATED_RAG_API_KEY_HERE" or not RAG_API_KEY:
        logger.critical("CRITICAL: RAG_API_KEY is not set or is default. Update 'open_webui_adapter.py'!")
        # exit(1) # Optionally prevent startup
    try:
        memory_backend.get_memory_collection() 
        logger.info("Memory Bank backend initialized for OpenWebUI Adapter.")
    except Exception as e:
        logger.error(f"FATAL: Could not initialize Memory Bank for OpenWebUI Adapter: {e}.")
    try: # Ping RAG server to check connectivity and auth
        ping_payload = {"query": "test", "n_results": 1}
        ping_headers = {RAG_API_KEY_NAME: RAG_API_KEY}
        requests.post(RAG_API_SERVER_URL, json=ping_payload, headers=ping_headers, timeout=5).raise_for_status()
        logger.info(f"RAG API server at {RAG_API_SERVER_URL} reachable and API key seems valid.")
    except requests.exceptions.HTTPError as http_err:
        if http_err.response.status_code == 403:
             logger.error(f"FATAL: RAG API key is invalid for RAG server at {RAG_API_SERVER_URL}. Key starts with '{RAG_API_KEY[:5]}...'. Please check both scripts.")
        else:
             logger.error(f"FATAL: Could not connect to RAG API server at {RAG_API_SERVER_URL} (HTTP Error): {http_err}")
    except requests.exceptions.RequestException as req_err:
        logger.error(f"FATAL: Could not connect to RAG API server at {RAG_API_SERVER_URL} (Request Error): {req_err}")
    try:
        ollama.list()
        logger.info(f"Ollama service reachable. Ensure '{LLM_MODEL_NAME}' is available.")
    except Exception as e:
        logger.error(f"FATAL: Ollama service not reachable for OpenWebUI Adapter: {e}.")


if __name__ == "__main__":
    logger.info(f"Starting OpenWebUI Adapter with Uvicorn on http://127.0.0.1:{OPENWEBUI_ADAPTER_PORT}")
    uvicorn.run(app, host="127.0.0.1", port=OPENWEBUI_ADAPTER_PORT, log_level="info")